# Generated by Django 5.0.2 on 2024-03-01 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProofOfConcept', '0004_alter_squirrel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('banned', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Sighting Time')),
                ('image', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(blank=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('squirrel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ProofOfConcept.squirrel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ProofOfConcept.user')),
            ],
        ),
    ]
